### ISSUE TITLE
WebODF rendering is broken in Chrome 44

### ISSUE THREAD

**Issue by longsleep** [kogmbh/WebODF#906] opened 2015-06-30 17:26 UTC
I just investigated why ODF's stopped to render properly. It turned out that Chrome 44 (currently in beta) does not render any ODF properly with WebODF.

I created a regression issue in Chromium tracker at https://code.google.com/p/chromium/issues/detail?id=505863

The Chromium issue includes a screen shot.

This should be fixed quickly as 44 will be released soon. 

No errors what so ever are logged on the WebODF side / Javascript console.

**Comment by adityab** [comment] 2015-07-01 09:31
Hi @longsleep, thanks for pointing this out.

This is a very serious regression from the Chromium side - apparently CSS styling doesn't work with non-HTML namespaced elements anymore, in both Chrome 44 beta and unstable.

I am going to weigh in there ASAP as such a change could be disastrous.

**Comment by adityab** [comment] 2015-07-01 13:15
### Diagnosis so far

Not all CSS rules inserted into a stylesheet using `insertRule` are actually applied in chrome.

### Case in point

On http://webodf.org/demo, you can see the webodf logo in the document.
This image (among other things) is not at all visible in Chromium 44 beta.

I ran the chrome debugger through `setImage` at https://github.com/kogmbh/WebODF/blob/master/webodf/lib/odf/OdfCanvas.js#L37, and inspected the `stylesheet` object that it inserts generated rules for the image dimensions, `background-image` etc into.

**This is what the rules in that stylesheet look like:**
![css-rules](https://cloud.githubusercontent.com/assets/591038/8454882/d5f7402c-2000-11e5-90ec-ca83967acae1.png)

**This is what the stylesheet's corresponding `<style>` element looks like:**
![style-tag](https://cloud.githubusercontent.com/assets/591038/8454896/f230bf3e-2000-11e5-829a-f135612f5087.png)

Note how the element doesn't have those rules within it's text content? That is perfectly normal; this happens with every browser  and stuff added with `insertRule` is stored in the browser's internal stylesheet representation and not actually visible in the DOM XML.

But then - I saved the stylesheet's `cssRules` field as a global object `temp1`, and the relevant `<style>` element as `temp2`, and **this is what the result of moving those rules into the `<style>` element's `textContent` looks like:**
![workaround](https://cloud.githubusercontent.com/assets/591038/8455184/14baa860-2003-11e5-93dc-7ee76be303b1.png)

### What next?

I'm going to write a simple test case for the Chromium folks to demonstrate if `insertRule` really is problematic.

In case we can't get this matter resolved with chromium, or figure out what WebODF is doing wrong - at least we now know a workaround, i.e., storing the generated style rules inline in a `<style>` element.

**Comment by adityab** [comment] 2015-07-01 17:38
I've confirmed that it is indeed a Chromium bug, and not WebODF using a deprecated API or something such. `insertRule` fails with namespaced attribute selectors. I've followed up on that issue with a test case and screenshot attached.

Fingers crossed, hopefully they won't release that without fixing it first in the stable channel.

**Comment by adityab** [comment] 2015-07-14 09:40
Happy to report that we got this fixed by the Chromium folks in time for the Chrome 44 stable; crisis averted, closing. :)

**Closed by adityab** 2015-07-14 09:40 UTC
Labels: chromium, regression, showstopper
